function SparsitySuccess = sparsitySuccessTest(ROWS, COLS, MAT_TYPE, SPARSITY_LIST, LOW_K, UPP_K, ITER,ALG)
% Generates a ROWS by COLS matrix and outputs a list with a row for each
% sparsity between LOW_K and UPP_K. The row corresponding to each k shall
% be the sum of 0,1-vectors generated by ITER runs of testOneMat.
SparsitySuccess=[];
for k=LOW_K:UPP_K
    SmallList=zeros(1,size(SPARSITY_LIST, 2));
    for i=1:ITER
        SmallList=SmallList+testOneMat(ROWS, COLS, MAT_TYPE, SPARSITY_LIST, k,ALG);
    end
    SparsitySuccess=[SparsitySuccess;SmallList]
end
